#! /usr/bin/bash

set -e

if [[ -z "$1" || -z "$2" || -z "$3" ]]; then
    echo "Usage: $0 <TypeName> <KeyType> <ValueType>" >&2
    exit 1
fi

TYPE="$1"
KEY="$2"
VALUE="$3"
LOWER=$(echo "$TYPE" | tr '[:upper:]' '[:lower:]')
OUTFILE="${LOWER}.gen.go"

cat > "$OUTFILE" <<EOF
package thehunted

// Code generated by map_methods.sh DO NOT EDIT.

import (
    "iter"
    "maps"
)

func (m ${TYPE}) Len() int {
    return len(m)
}

func (m ${TYPE}) Get(key ${KEY}) (${VALUE}, bool) {
    v, ok := m[key]
    return v, ok
}

func (m ${TYPE}) All() iter.Seq2[${KEY}, ${VALUE}] {
    return maps.All(m)
}

func (m ${TYPE}) Keys() iter.Seq[${KEY}] {
    return maps.Keys(m)
}

func (m ${TYPE}) Values() iter.Seq[${VALUE}] {
    return maps.Values(m)
}
EOF

go fmt "$OUTFILE"

echo "Generated ${OUTFILE}"
