package thehunted

// Code generated by map_viewer_methods.sh DO NOT EDIT.

import (
	"iter"
	"maps"
)

func (m TorpLayout) Len() int {
	return len(m)
}

func (m TorpLayout) Get(key TorpLoc) (TorpCountsView, bool) {
	v, ok := m[key]
	return v.View(), ok
}

func (m TorpLayout) All() iter.Seq2[TorpLoc, TorpCountsView] {
	return func(yield func(TorpLoc, TorpCountsView) bool) {
		for k, v := range m {
			if !yield(k, v.View()) {
				return
			}
		}
	}
}

func (m TorpLayout) Keys() iter.Seq[TorpLoc] {
	return maps.Keys(m)
}

func (m TorpLayout) Values() iter.Seq[TorpCountsView] {
	return func(yield func(TorpCountsView) bool) {
		for _, v := range m {
			if !yield(v.View()) {
				return
			}
		}
	}
}

func (m TorpLayout) View() TorpLayoutView {
	return m
}
