package thehunted

// Code generated by map_methods.sh DO NOT EDIT.

import (
	"iter"
	"maps"
)

func (m TorpCountsData) Len() int {
	return len(m)
}

func (m TorpCountsData) Get(key TorpType) (int, bool) {
	v, ok := m[key]
	return v, ok
}

func (m TorpCountsData) All() iter.Seq2[TorpType, int] {
	return maps.All(m)
}

func (m TorpCountsData) Keys() iter.Seq[TorpType] {
	return maps.Keys(m)
}

func (m TorpCountsData) Values() iter.Seq[int] {
	return maps.Values(m)
}
